### ISSUE TITLE
Tutorial Diagrams

### ISSUE THREAD

**Issue by chopov1** [IAMColumbia/ApocolypseTrain#76]
Pictures for tutorial that go on ground and can be walked on top of

(look into maybe doing gifs?)

Controls for moving shooting and dashing
Controls for Dash
Controls for picking items up, and holding to open loot boxes
Explain weapon pickups
Explain bringing fuel to train
Explain Distance traveled

**Comment by Maleahristau** [comment]
https://docs.google.com/document/d/1j_lXiQgxWHfovwYl2QX4XPdChhazAhe-Zg_iqkuPL8g/edit?usp=sharing
